export const sexs = ["Masculino", "Femenino", "Otro"];

export const locations = {
  Amazonas: {
    Bagua: ["Aramango", "Bagua", "Copallín", "El Parco", "Imaza", "La Peca"],
    Bongará: [
      "Chisquilla",
      "Churuja",
      "Corosha",
      "Cuispes",
      "Florida",
      "Jazán",
      "Jumbilla",
      "Recta",
      "San Carlos",
      "Shipasbamba",
      "Valera",
      "Yambrasbamba",
    ],
    Chachapoyas: [
      "Asunción",
      "Balsas",
      "Chachapoyas",
      "Cheto",
      "Chiliquin",
      "Chuquibamba",
      "Granada",
      "Huancas",
      "La Jalca",
      "Levanto",
      "Leymebamba",
      "Magdalena",
      "Mariscal Castilla",
      "Molinopampa",
      "Montevideo",
      "Olleros",
      "Quinjalca",
      "San Francisco de Daguas",
      "San Isidro de Maino",
      "Soloco",
      "Sonche",
    ],
    Condorcanqui: ["El Cenepa", "Río Santiago", "Santa María de Nieva"],
    Luya: [
      "Camporredondo",
      "Cocabamba",
      "Colcamar",
      "Conila",
      "Inguilpata",
      "Longuita",
      "Lonya Chico",
      "Luya",
      "Luya Viejo",
      "Lámud",
      "María",
      "Ocalli",
      "Ocumal",
      "Pisuquía",
      "Providencia",
      "San Cristóbal",
      "San Francisco del Yeso",
      "San Jerónimo",
      "San Juan de Lopecancha",
      "Santa Catalina",
      "Santo Tomás",
      "Tingo",
      "Trita",
    ],
    "Rodríguez de Mendoza": [
      "Chirimoto",
      "Cochamal",
      "Huambo",
      "Limabamba",
      "Longar",
      "Mariscal Benavides",
      "Milpuc",
      "Omia",
      "San Nicolás",
      "Santa Rosa",
      "Totora",
      "Vista Alegre",
    ],
    Utcubamba: [
      "Bagua Grande",
      "Cajaruro",
      "Cumba",
      "El Milagro",
      "Jamalca",
      "Lonya Grande",
      "Yamón",
    ],
  },
  Ancash: {
    Aija: ["Aija", "Coris", "Huacllán", "La Merced", "Succha"],
    "Antonio Raymondi": [
      "Aczo",
      "Chaccho",
      "Chingas",
      "Llamellín",
      "Mirgas",
      "San Juan de Rontoy",
    ],
    Asunción: ["Acochaca", "Chacas"],
    Bolognesi: [
      "Abelardo Pardo Lezameta",
      "Antonio Raymondi",
      "Aquia",
      "Cajacay",
      "Canis",
      "Chiquián",
      "Colquioc",
      "Huallanca",
      "Huasta",
      "Huayllacayán",
      "La Primavera",
      "Mangas",
      "Pacllón",
      "San Miguel de Corpanqui",
      "Tauripo",
      "Ticllos",
    ],
    Carhuaz: [
      "Acopampa",
      "Amashca",
      "Anta",
      "Ataquero",
      "Carhuac",
      "Carhuaz",
      "Marcará",
      "Pariahuanca",
      "San Miguel de Aco",
      "Shilla",
      "Tinco",
      "Yungar",
    ],
    "Carlos Fermín Fitzcarrald": ["San Luis", "San Nicolás", "Yauya"],
    Casma: [
      "Buena Vista Alta",
      "Casma",
      "Comandante Noel",
      "Puerto Casma",
      "Yaután",
    ],
    Corongo: [
      "Aco",
      "Bambas",
      "Corongo",
      "Cusca",
      "La Pampa",
      "Yanac",
      "Yupán",
    ],
    Huaraz: [
      "Cochabamba",
      "Colcabamba",
      "Huanchay",
      "Huaraz",
      "Independencia",
      "Jangas",
      "La Libertad",
      "Olleros",
      "Pampas",
      "Pariacoto",
      "Pira",
      "Tarica",
    ],
    Huari: [
      "Anra",
      "Cajay",
      "Chavín de Huantar",
      "Huacachi",
      "Huacchis",
      "Huachis",
      "Huantar",
      "Huari",
      "Masin",
      "Paucas",
      "Pontó",
      "Rahuapampa",
      "Rapayán",
      "San Marcos",
      "San Pedro de Chaná",
      "Uco",
    ],
    Huarmey: ["Cochapeti", "Culebras", "Huarmey", "Huayan", "Malvas"],
    Huaylas: [
      "Caraz",
      "Huallanca",
      "Huata",
      "Huaylas",
      "Mato",
      "Pamparomas",
      "Pueblo Libre",
      "Santa Cruz",
      "Santo Toribio",
      "Yuracmarca",
    ],
    "Mariscal Luzuriaga": [
      "Casca",
      "Eleazar Guzmán Barrón",
      "Fidel OIivas Escudero",
      "Llama",
      "Llumpa",
      "Lucma",
      "Musga",
      "Piscobamba",
    ],
    Ocros: [
      "Acas",
      "Cajamarquilla",
      "Carhuapampa",
      "Cochas",
      "Congas",
      "Llipa",
      "Ocros",
      "San Cristóbal de Raján",
      "San Pedro",
      "Santiago de Chilcas",
    ],
    Pallasca: [
      "Bolognesi",
      "Cabana",
      "Conchucos",
      "Huacaschuque",
      "Huandoval",
      "Lacabamba",
      "Llapo",
      "Pallasca",
      "Pampas",
      "Santa Rosa",
      "Tauca",
    ],
    Pomabamba: ["Huayllan", "Parobamba", "Pomabamba", "Quinuabamba"],
    Recuay: [
      "Catac",
      "Cotaparaco",
      "Huayllapampa",
      "Llacllín",
      "Marca",
      "Pampas Chico",
      "Pararín",
      "Recuay",
      "Tapacocha",
      "Ticapampa",
    ],
    Santa: [
      "Chimbote",
      "Coishco",
      "Cáceres del Perú",
      "La Caleta",
      "La Huaca",
      "La Libertad",
      "Macate",
      "Moro",
      "Nepeña",
      "Nuevo Chimbote",
      "Samanco",
      "San Juan",
      "Santa",
    ],
    Sihuas: [
      "Acobamba",
      "Alfonso Ugarte",
      "Cashapampa",
      "Chingalpo",
      "Huayllabamba",
      "Quiches",
      "Ragash",
      "San Juan",
      "Sicsibamba",
      "Sihuas",
    ],
    Yungay: [
      "Cascapara",
      "Mancos",
      "Matacoto",
      "Quillo",
      "Ranrahirca",
      "Shupluy",
      "Yanama",
      "Yungay",
    ],
  },
  Apurimac: {
    Abancay: [
      "Abancay",
      "Chacoche",
      "Circa",
      "Curahuasi",
      "Huanipaca",
      "Lambrama",
      "Pichirhua",
      "San Pedro de Cachora",
      "Tamburco",
    ],
    Andahuaylas: [
      "Andahuaylas",
      "Andarapa",
      "Chiara",
      "Huancarama",
      "Huancaray",
      "Huayana",
      "Kaquiabamba",
      "Kishuara",
      "Pacobamba",
      "Pacucha",
      "Pampachiri",
      "Pomacocha",
      "San Antonio de Cachi",
      "San Jerónimo",
      "San Miguel de Chaccrapampa",
      "Santa María de Chicmo",
      "Talavera de la Reyna",
      "Tumay Huaraca",
      "Turpo",
    ],
    Antabamba: [
      "Antabamba",
      "El Oro",
      "Huaquirca",
      "Juan Espinoza Medrano",
      "Oropesa",
      "Pachaconas",
      "Sabaino",
    ],
    Aymaraes: [
      "Capaya",
      "Caraybamba",
      "Chalhuanca",
      "Chapimarca",
      "Colcabamba",
      "Cotaruse",
      "Huayllu",
      "Justo Apu Sahuaraura",
      "Lucre",
      "Pocohuanca",
      "San Juan de Chacña",
      "Sañayca",
      "Soraya",
      "Tapairihua",
      "Tintay",
      "Toraya",
      "Yanaca",
    ],
    Chincheros: [
      "Anco-Huallo",
      "Chincheros",
      "Cocharcas",
      "Huaccana",
      "Ocobamba",
      "Ongoy",
      "Ranracancha",
      "Uranmarca",
    ],
    Cotabambas: [
      "Chalhuahuacho",
      "Cotabambas",
      "Coyllurqui",
      "Haquira",
      "Mara",
      "Tambobamba",
    ],
    Grau: [
      "Chuquibambilla",
      "Curasco",
      "Curpahuasi",
      "Gamarra",
      "Huayllati",
      "Mamara",
      "Micaela Bastidas",
      "Pataypampa",
      "Progreso",
      "San Antonio",
      "Santa Rosa",
      "Turpay",
      "Vilcabamba",
      "Virundo",
    ],
  },
  Arequipa: {
    Arequipa: [
      "Alto Selva Alegre",
      "Arequipa",
      "Cayma",
      "Cerro Colorado",
      "Characato",
      "Chiguata",
      "Jacobo Hunter",
      "José Luis Bustamante y Rivero",
      "La Joya",
      "Mariano Melgar",
      "Miraflores",
      "Mollebaya",
      "Paucarpata",
      "Pocsi",
      "Polobaya",
      "Quequeña",
      "Sabandía",
      "Sachaca",
      "San Juan de Siguas",
      "San Juan de Tarucani",
      "Santa Isabel de Siguas",
      "Santa Rita de Siguas",
      "Socabaya",
      "Tiabaya",
      "Uchumayo",
      "Vitor",
      "Yanahuara",
      "Yarabamba",
      "Yura",
    ],
    Camaná: [
      "Camaná",
      "José María Quimper",
      "Mariano Nicolás Valcarcel",
      "Mariscal Cáceres",
      "Nicolás de Piérola",
      "Ocoña",
      "Quilca",
      "Samuel Pastor",
    ],
    Caravelí: [
      "Acarí",
      "Atico",
      "Atiquipa",
      "Bella Unión",
      "Cahuacho",
      "Caravelí",
      "Chala",
      "Chaparra",
      "Huanuhuanu",
      "Jaqui",
      "Lomas",
      "Quicacha",
      "Yauca",
    ],
    Castilla: [
      "Andahua",
      "Aplao",
      "Ayo",
      "Chachas",
      "Chilcaymarca",
      "Choco",
      "Huancarqui",
      "Machaguay",
      "Orcopampa",
      "Pampacolca",
      "Tipán",
      "Uraca",
      "Uñón",
      "Viraco",
    ],
    Caylloma: [
      "Achoma",
      "Cabanaconde",
      "Callalli",
      "Caylloma",
      "Chivay",
      "Coporaque",
      "Huambo",
      "Huanca",
      "Ichupampa",
      "Lari",
      "Lluta",
      "Maca",
      "Madrigal",
      "Majes",
      "San Antonio de Chuca",
      "Sibayo",
      "Tapay",
      "Tisco",
      "Tuti",
      "Yanque",
    ],
    Condesuyos: [
      "Andaray",
      "Cayarani",
      "Chichas",
      "Chuquibamba",
      "Iray",
      "Rio Grande",
      "Salamanca",
      "Yanaquihua",
    ],
    Islay: [
      "Cocachacra",
      "Dean Valdivia",
      "Islay",
      "Mejía",
      "Mollendo",
      "Punta de Bombón",
    ],
    "La Unión": [
      "Alca",
      "Charcana",
      "Cotahuasi",
      "Huaynacotas",
      "Pampamarca",
      "Puyca",
      "Quechualla",
      "Sayla",
      "Tauría",
      "Tomepampa",
      "Toro",
    ],
  },
  Ayacucho: {
    Cangayo: [
      "Cangayo",
      "Chuschi",
      "Los Morochucos",
      "María Parado de Bellido",
      "Paras",
      "Totos",
    ],
    Huamanga: [
      "Acocro",
      "Acos Vinchos",
      "Andrés Avelino Cáceres",
      "Ayacucho",
      "Carmen Alto",
      "Chiara",
      "Huamanga",
      "Jesús Nazareno",
      "Ocros",
      "Pacaycasa",
      "Quinua",
      "San José de Ticllas",
      "San Juan Bautista",
      "Santiago de Pischa",
      "Socos",
      "Tambillo",
      "Vinchos",
    ],
    Huancasancos: ["Carapo", "Sacsamarca", "Sancos", "Santiago de Lucanamarca"],
    Huanta: [
      "Ayahuanco",
      "Huamanguilla",
      "Huanta",
      "Iguain",
      "Llochegua",
      "Luricocha",
      "Santillana",
      "Sivia",
    ],
    "La Mar": [
      "Anco",
      "Ayna",
      "Chilcas",
      "Chungui",
      "Luis Carranza",
      "San Miguel",
      "Santa Rosa",
      "Tambo",
    ],
    Lucanas: [
      "Aucara",
      "Cabana",
      "Carmen Salcedo",
      "Chaviña",
      "Chipao",
      "Huac-Huas",
      "Laramate",
      "Leoncio Prado",
      "Llauta",
      "Lucanas",
      "Ocaña",
      "Otoca",
      "Puquio",
      "Saisa",
      "San Cristóbal",
      "San Juan",
      "San Pedro",
      "San Pedro de Palco",
      "Sancos",
      "Santa Ana de Huaycahuacho",
      "Santa Lucía",
    ],
    Parinacochas: [
      "Chumpi",
      "Coracora",
      "Coronel Castañeda",
      "Pacapausa",
      "Pullo",
      "Puyusca",
      "San Francisco de Ravacayco",
      "Upahuacho",
    ],
    "Paucar del Sara Sara": [
      "Colta",
      "Corculla",
      "Lampa",
      "Marcabamba",
      "Oyolo",
      "Pararca",
      "Pauza",
      "San Javier de Alpabamba",
      "San José de Ushua",
      "Sara Sara",
    ],
    Sucre: [
      "Belén",
      "Chalcos",
      "Chilcayoc",
      "Huacaña",
      "Morcolla",
      "Paico",
      "Querobamba",
      "San Pedro de Larcay",
      "San Salvador de Quije",
      "Santiago de Paucaray",
      "Soras",
    ],
    "Victor Fajardo": [
      "Alcamenca",
      "Apongo",
      "Asquipata",
      "Canaria",
      "Cayara",
      "Colca",
      "Huamanquiquia",
      "Huancapi",
      "Huancaraylla",
      "Huaya",
      "Sarhua",
      "Vilcanchos",
    ],
    "Vilcas Huamán": [
      "Accomarca",
      "Carhuanca",
      "Concepción",
      "Huambalpa",
      "Independencia",
      "Saurama",
      "Vilcas Huamán",
      "Vischongo",
    ],
  },
  Cajamarca: {
    Cajabamba: ["Cachachi", "Cajabamba", "Condebamba", "Sitacocha"],
    Cajamarca: [
      "Asunción",
      "Cajamarca",
      "Chetilla",
      "Cospán",
      "Jesús",
      "La Encañada",
      "Llacanora",
      "Los Baños del Inca",
      "Magdalena",
      "Matará",
      "Namora",
      "San Juan",
    ],
    Celendín: [
      "Celendín",
      "Chumuch",
      "Cortegana",
      "Huasmin",
      "Jorge Chávez",
      "José Gálvez",
      "La Libertad de Pallán",
      "Miguel Iglesias",
      "Oxamarca",
      "Sorochuco",
      "Sucre",
      "Utco",
    ],
    Chota: [
      "Anguía",
      "Chadín",
      "Chalamarca",
      "Chiguirip",
      "Chimban",
      "Choropampa",
      "Chota",
      "Cochabamba",
      "Conchán",
      "Huambos",
      "Lajas",
      "Llama",
      "Miracosta",
      "Paccha",
      "Pión",
      "Querocoto",
      "San Juan de Licupis",
      "Tacabamba",
      "Tocmoche",
    ],
    Contumazá: [
      "Chilete",
      "Contumazá",
      "Cupisnique",
      "Guzmango",
      "San Benito",
      "Santa Cruz de Toledo",
      "Tantarica",
      "Yonán",
    ],
    Cutervo: [
      "Callayuc",
      "Choros",
      "Cujillo",
      "Cutervo",
      "La Ramada",
      "Pimpingos",
      "Querocotillo",
      "San Andrés de Cutervo",
      "San Juan de Cutervo",
      "San Luis de Lucma",
      "Santa Cruz",
      "Santo Domingo de la Capilla",
      "Santo Tomás",
      "Socota",
      "Toribio Casanova",
    ],
    Hualgayoc: ["Bambamarca", "Chugur", "Hualgayoc"],
    Jaén: [
      "Bellavista",
      "Chontali",
      "Colasay",
      "Huabal",
      "Jaén",
      "Las Pirias",
      "Pomahuaca",
      "Pucará",
      "Sallique",
      "San Felipe",
      "San José del Alto",
      "Santa Rosa",
    ],
    "San Ignacio": [
      "Chirinos",
      "Huarango",
      "La Coipa",
      "Namballe",
      "San Ignacio",
      "San José de Lourdes",
      "Tabaconas",
    ],
    "San Marcos": [
      "Chancay",
      "Eduardo Villanueva",
      "Gregorio Pita",
      "Ichocan",
      "José Manuel Quiroz",
      "José Sabogal",
      "San Marcos",
    ],
    "San Miguel": [
      "Bolívar",
      "Calquis",
      "Catilluc",
      "El Prado",
      "La Florida",
      "Llapa",
      "Nanchoc",
      "Niepos",
      "San Gregorio",
      "San Miguel de Pallaques",
      "San Silvestre de Cochan",
      "Tongod",
      "Unión Agua Blanca",
    ],
    "San Pablo": ["San Bernardino", "San Luis", "San Pablo", "Tumbaden"],
    "Santa Cruz": [
      "Andabamba",
      "Catache",
      "Chancaybaños",
      "La Esperanza",
      "Ninabamba",
      "Pulán",
      "Santa Cruz",
      "Saucepampa",
      "Sexi",
      "Uticyacu",
      "Yauyucan",
    ],
  },
  Cusco: {
    Acomayo: [
      "Acomayo",
      "Acopia",
      "Acos",
      "Mosoc Llacta",
      "Pomacanchi",
      "Rondocan",
      "Sangarará",
    ],
    Anta: [
      "Ancahuasi",
      "Anta",
      "Cachimayo",
      "Chinchaypujio",
      "Huarocondo",
      "Limatambo",
      "Mollepata",
      "Pucyura",
      "Zurite",
    ],
    Calca: [
      "Calca",
      "Coya",
      "Lamay",
      "Lares",
      "Pisac",
      "San Salvador",
      "Taray",
      "Yanatile",
    ],
    Canas: [
      "Checca",
      "Kunturkanki",
      "Langui",
      "Layo",
      "Pampamarca",
      "Quehue",
      "Tupac Amaru",
      "Yanaoca",
    ],
    Canchis: [
      "Checacupe",
      "Combapata",
      "Marangani",
      "Pitumarca",
      "San Pablo",
      "San Pedro",
      "Sicuani",
      "Tinta",
    ],
    Chumbivilcas: [
      "Capacmarca",
      "Chamaca",
      "Colquemarca",
      "Livitaca",
      "Llusco",
      "Quiñota",
      "Santo Tomás",
      "Velille",
    ],
    Cusco: [
      "Ccorca",
      "Cusco",
      "Poroy",
      "San Jerónimo",
      "San Sebastián",
      "Santiago",
      "Saylla",
      "Wanchaq",
    ],
    Espinar: [
      "Alto Pichigua",
      "Condoroma",
      "Coporaque",
      "Espinar",
      "Ocoruro",
      "Pallpata",
      "Pichigua",
      "Suyckutambo",
    ],
    "La Convención": [
      "Echarate",
      "Huayopata",
      "Kimbiri",
      "Maranura",
      "Ocobamba",
      "Pichari",
      "Quellouno",
      "Quillabamba",
      "Santa Ana",
      "Santa Teresa",
      "Vilcabamba",
    ],
    Paruro: [
      "Accha",
      "Ccapi",
      "Colcha",
      "Huanoquite",
      "Omacha",
      "Paccaritambo",
      "Paruro",
      "Pillpinto",
      "Yaurisque",
    ],
    Paucartambo: [
      "Caicay",
      "Challabamba",
      "Colquepata",
      "Huancarani",
      "Kosñipata",
      "Paucartambo",
    ],
    Quispicanchi: [
      "Andahuaylillas",
      "Camanti",
      "Ccarhuayo",
      "Ccatca",
      "Cusipata",
      "Huaro",
      "Lucre",
      "Marcapata",
      "Ocongate",
      "Oropesa",
      "Quiquijana",
      "Urcos",
    ],
    Urubamba: [
      "Chinchero",
      "Huayllabamba",
      "Macchupicchu",
      "Maras",
      "Ollantaytambo",
      "Urubamba",
      "Yucay",
    ],
  },
  Huancavelica: {
    Acobamba: [
      "Acobamba",
      "Andabamba",
      "Anta",
      "Caja",
      "Marcas",
      "Paucará",
      "Pomacocha",
      "Rosario",
    ],
    Angaraes: [
      "Anchonga",
      "Callanmarca",
      "Ccochaccasa",
      "Chincho",
      "Congalla",
      "Huanca-Huanca",
      "Huayllay Grande",
      "Julcamarca",
      "Lircay",
      "San Antonio de Antaparco",
      "Santo Tomás de Pata",
      "Secclla",
    ],
    Castrovirreyna: [
      "Arma",
      "Aurahuá",
      "Capillas",
      "Castrovirreyna",
      "Chupamarca",
      "Cocas",
      "Huachos",
      "Huamatambo",
      "Mollepampa",
      "San Juan",
      "Santa Ana",
      "Tantara",
      "Ticrapo",
    ],
    Churcampa: [
      "Anco",
      "Chinchihuasi",
      "Churcampa",
      "El Carmen",
      "La Merced",
      "Locroja",
      "Pachamarca",
      "Paucarbamba",
      "San Miguel de Mayocc",
      "San Pedro de Coris",
    ],
    Huancavelica: [
      "Acobambilla",
      "Acoria",
      "Ascención",
      "Conayca",
      "Cuenca",
      "Huachocolpa",
      "Huancavelica",
      "Huando",
      "Huayllahuara",
      "Izcuchaca",
      "Laria",
      "Manta",
      "Mariscal Cáceres",
      "Moya",
      "Nueva Occoro",
      "Palca",
      "Pilchaca",
      "Vilca",
      "Yauli",
    ],
    Huaytará: [
      "Ayaví",
      "Córdova",
      "Huayacundo Arma",
      "Huaytará",
      "Laramarca",
      "Ocoyo",
      "Pilpichaca",
      "Querco",
      "Quito-Arma",
      "San Antonio de Cusicancha",
      "San Francisco de Sangayaico",
      "San Isidro",
      "Santiago de Chocorvos",
      "Santiago de Quirahuara",
      "Santo Domingo de Capillas",
      "Tambo",
    ],
    Tayacaja: [
      "Acostambo",
      "Acraquía",
      "Ahuaycha",
      "Colcabamba",
      "Daniel Hernández",
      "Huachocolpa",
      "Huaribamba",
      "Pampas",
      "Pazos",
      "Quishuar",
      "Salcabamba",
      "Salcahuasi",
      "San Marcos de Rocchac",
      "Surcubamba",
      "Tintay Puncu",
      "Ñahuimpuquio",
    ],
  },
  Huanuco: {
    Ambo: [
      "Ambo",
      "Cayna",
      "Colpas",
      "Conchamarca",
      "Huacar",
      "San Francisco",
      "San Rafael",
      "Tomay Kichwa",
    ],
    "Dos de Mayo": [
      "Chuquis",
      "La Unión",
      "Marías",
      "Pachas",
      "Quivilla",
      "Ripán",
      "Shunqui",
      "Sillapata",
      "Yanas",
    ],
    Huacaybamba: ["Canchabamba", "Cochabamba", "Huacaybamba", "Pinra"],
    Huamalíes: [
      "Arancay",
      "Chavín de Pariarca",
      "Jacas Grande",
      "Jarqui",
      "Llata",
      "Miraflores",
      "Monzón",
      "Punchao",
      "Puños",
      "Singa",
      "Tantamayo",
    ],
    Huánuco: [
      "Amarilis",
      "Chinchao",
      "Churumbamba",
      "Huánuco",
      "Lauricocha",
      "Margos",
      "Quisqui",
      "San Francisco de Cayrán",
      "Santa María del Valle",
      "Yarumayo",
    ],
    Lauricocha: [
      "Baños",
      "Jesús",
      "Jivia",
      "Queropalca",
      "Rondos",
      "San Francisco de Asís",
      "San Miguel de Cauri",
    ],
    "Leoncio Prado": [
      "Daniel Alomía Robles",
      "Hermilio Valdizán",
      "José Crespo y Castillo",
      "Luyando",
      "Mariano Dámaso Beraún",
      "Rupa-Rupa",
      "Tingo María",
    ],
    Marañón: ["Cholón", "Hucrachuco", "San Buenaventura"],
    Pachitea: ["Chaglla", "Molino", "Panao", "Umari"],
    "Puerto Inca": [
      "Codo del Pozuzo",
      "Honoria",
      "Puerto Inca",
      "Tournavista",
      "Yuyapichis",
    ],
    Yarowilca: [
      "Aparicio Pomares",
      "Cahuac",
      "Chacabamba",
      "Chavinillo",
      "Choras",
      "Chupan",
      "Jacas Chico",
      "Obas",
      "Pampamarca",
    ],
  },
  Ica: {
    Chincha: [
      "Alto Larán",
      "Chavín",
      "Chincha Alta",
      "Chincha Baja",
      "El Carmen",
      "Grocio Prado",
      "Pueblo Nuevo",
      "San Juan de Yanac",
      "San Pedro de Huacarpana",
      "Sunampe",
      "Tambo de Mora",
    ],
    Ica: [
      "Ica",
      "La Tinguiña",
      "Los Aquijes",
      "Ocucaje",
      "Pachacutec",
      "Parcona",
      "Pueblo Nuevo",
      "Salas",
      "San José de los Molinos",
      "San Juan Bautista",
      "Santiago",
      "Subtanjalla",
      "Tate",
      "Yauca del Rosario",
    ],
    Nazca: ["Changuillo", "El Ingenio", "Marcona", "Nazca", "Vista Alegre"],
    Palpa: ["Ica", "Llipata", "Palpa", "Río Grande", "Santa Cruz", "Tibillo"],
    Pisco: [
      "Huancano",
      "Humay",
      "Independencia",
      "Paracas",
      "Pisco",
      "San Andrés",
      "San Clemente",
      "Tupac Amaru Inca",
    ],
  },
  Junin: {
    Chanchamayo: [
      "Chanchamayo",
      "Perené",
      "Pichanaqui",
      "San Luis de Shuaro",
      "San Ramón",
      "Vitoc",
    ],
    Chupaca: [
      "Ahuac",
      "Chongos Bajo",
      "Chupaca",
      "Huachac",
      "Huamancaca Chico",
      "San Juan de Jarpa",
      "San Juan de Yscos",
      "Tres de Diciembre",
      "Yanacancha",
    ],
    Concepción: [
      "Aco",
      "Andamarca",
      "Chambara",
      "Cochas",
      "Comas",
      "Concepción",
      "Heroínas Toledo",
      "Manzanares",
      "Mariscal Castilla",
      "Matahuasi",
      "Mito",
      "Nueve de Julio",
      "Orcotuna",
      "San José de Quero",
      "Santa Rosa de Ocopa",
    ],
    Huancayo: [
      "Carhuacallanga",
      "Chacapampa",
      "Chicche",
      "Chilca",
      "Chongos Alto",
      "Chupuro",
      "Colca",
      "Cullhuas",
      "El Tambo",
      "Huacrapuquio",
      "Hualhuas",
      "Huancayo",
      "Huancán",
      "Huasicancha",
      "Huayucachi",
      "Ingenio",
      "Pariahuanca",
      "Pilcomayo",
      "Pucará",
      "Qhichuay",
      "Quilcas",
      "San Agustín de Cajas",
      "San Pedro de Saño",
      "Santo Domingo de Acobamba",
      "Sapallanga",
      "Sicaya",
      "Viques",
    ],
    Jauja: [
      "Acolla",
      "Apata",
      "Ataura",
      "Canchayllo",
      "Curicaca",
      "Huamalí",
      "Huaripampa",
      "Huertas",
      "Janjaillo",
      "Jauja",
      "Julcán",
      "Leonor Ordóñez",
      "Llocllapampa",
      "Marco",
      "Masma",
      "Masma Chico",
      "Molinos",
      "Monobamba",
      "Muqui",
      "Muquiyauyo",
      "Paca",
      "Paccha",
      "Pancán",
      "Parco",
      "Pomacancha",
      "Ricrán",
      "San Lorenzo",
      "San Pedro de Chunán",
      "Sausa",
      "Sincos",
      "Tunan Marca",
      "Yauli",
      "Yauyos",
    ],
    Junín: ["Carhuamayo", "Junín", "Ondores", "Ulcumayo"],
    Satipo: [
      "Coviriali",
      "Llaylla",
      "Mazamari",
      "Pampa Hermosa",
      "Pangoa",
      "Río Negro",
      "Río Tambo",
      "Satipo",
    ],
    Tarma: [
      "Acobamba",
      "Huaricolca",
      "Huasahuasi",
      "La Unión",
      "Palca",
      "Palcamayo",
      "San Pedro de Cajas",
      "Tapo",
      "Tarma",
    ],
    Yauli: [
      "Chacapalpa",
      "Huay-Huay",
      "La Oroya",
      "Marcapomacocha",
      "Morococha",
      "Paccha",
      "Santa Barbara de Carhuacayán",
      "Santa Rosa de Sacco",
      "Suitucancha",
      "Yauli",
    ],
  },
  "La Libertad": {
    Ascope: [
      "Ascope",
      "Casa Grande",
      "Chicama",
      "Chocope",
      "Magdalena de Cao",
      "Paiján",
      "Rázuri",
      "Santiago de Cao",
    ],
    Bolívar: [
      "Bambamarca",
      "Bolívar",
      "Condormarca",
      "Longotea",
      "Uchumarca",
      "Ucuncha",
    ],
    Chepén: ["Chepén", "Pacanga", "Pueblo Nuevo"],
    "Gran Chimú": ["Cascas", "Lucma", "Marmot", "Sayapullo"],
    Julcan: ["Calamarca", "Carabamba", "Huaso", "Julcan"],
    Otuzco: [
      "Agallpampa",
      "Charat",
      "Huaranchal",
      "Mache",
      "Otuzco",
      "Paranday",
      "Salpo",
      "Sinsicap",
      "Usquil",
      "La Cuesta",
    ],
    Pacasmayo: [
      "Guadalupe",
      "Jequetepeque",
      "Pacasmayo",
      "San Jose",
      "San Pedro De Lloc",
    ],
    Pataz: [
      "Buldibuyo",
      "Chillia",
      "Huancaspata",
      "Huaylillas",
      "Huayo",
      "Ongon",
      "Parcoy",
      "Patáz",
      "Pías",
      "Taurija",
      "Tayabamba",
      "Urpay",
      "Santiago De Challas",
    ],
    Trujillo: [
      "El Porvenir",
      "Florencia de Mora",
      "Huanchaco",
      "La Esperanza",
      "Laredo",
      "Moche",
      "Poroto",
      "Salaverry",
      "Simbal",
      "Trujillo",
      "Victor Larco Herrera",
    ],
    Virú: ["Chao", "Guadalupito", "Virú"],
    "Sanchez Carrion": [
      "Chugay",
      "Cochorco",
      "Curgos",
      "Huamachuco",
      "Marcabal",
      "Sanagoran",
      "Sarin",
      "Sartimbamba",
    ],
    "Santiago De Chuco": [
      "Angasmarca",
      "Cachicadán",
      "Calipuy",
      "Mollebamba",
      "Mollepata",
      "Quiruvilca",
      "Santa Cruz De Chuca",
      "Santiago De Chuco",
      "Sitabamba",
    ],
  },
  Lambayeque: {
    Chiclayo: [
      "Cayalti",
      "Chiclayo",
      "Chongoyape",
      "Etén",
      "José Leonardo Ortiz",
      "La Victoria",
      "Lagunas",
      "Monsefu",
      "Nueva Arica",
      "Oyotún",
      "Patapo",
      "Picsi",
      "Pimentel",
      "Pomalca",
      "Pucalá",
      "Puerto Etén",
      "Reque",
      "Santa Rosa",
      "Saña",
      "Tumán",
    ],
    Ferreñafe: [
      "Cañaris",
      "Ferreñafe",
      "Incahuasi",
      "Manuel Antonio Mesones Muro",
      "Pitipo",
      "Pueblo Nuevo",
    ],
    Lambayeque: [
      "Chochope",
      "Illimo",
      "Jayanca",
      "Lambayeque",
      "Mochumi",
      "Morrope",
      "Motupe",
      "Olmos",
      "Pacora",
      "Salas",
      "San José",
      "Túcume",
    ],
  },
  "Lima Metropolitana": {
    Ancón: [],
    Ate: [],
    Barranco: [],
    Bellavista: [],
    Breña: [],
    Callao: [],
    Carabayllo: [],
    "Carmen de la Legua Reynoso": [],
    Chaclacayo: [],
    Chorrillos: [],
    Cieneguilla: [],
    Comas: [],
    "El Agustino": [],
    Independencia: [],
    "Jesús María": [],
    "La Molina": [],
    "La Perla": [],
    "La Punta": [],
    "La Victoria": [],
    Lima: [],
    Lince: [],
    "Los Olivos": [],
    Lurigancho: [],
    Lurín: [],
    "Magdalena del Mar": [],
    "Mi Perú": [],
    Miraflores: [],
    Pachacámac: [],
    Pucusana: [],
    "Pueblo Libre": [],
    "Puente Piedra": [],
    "Punta Hermosa": [],
    "Punta Negra": [],
    Rimac: [],
    "San Bartolo": [],
    "San Borja": [],
    "San Isidro": [],
    "San Juan de Lurigancho": [],
    "San Juan de Miraflores": [],
    "San Luis": [],
    "San Martín de Porres": [],
    "San Miguel": [],
    "Santa Anita": [],
    "Santa María del Mar": [],
    "Santa Rosa": [],
    "Santiago de Surco": [],
    Surquillo: [],
    Ventanilla: [],
    "Villa El Salvador": [],
    "Villa María del Triunfo": [],
  },
  "Lima Provincias": {
    Barranca: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"],
    Cajatambo: ["Cajatambo", "Copa", "Gorgor", "Huancapón", "Manás"],
    Canta: [
      "Arahuay",
      "Canta",
      "Huamantanga",
      "Huaros",
      "Lachaqui",
      "San Buenaventura",
      "Santa Rosa de Quives",
    ],
    Cañete: [
      "Asia",
      "Calango",
      "Cerro Azul",
      "Chilca",
      "Coayllo",
      "Imperial",
      "Lunahuaná",
      "Mala",
      "Nuevo Imperial",
      "Pacarán",
      "Quilmaná",
      "San Antonio",
      "San Luis",
      "San Vicente de Cañete",
      "Santa Cruz de Flores",
      "Zúñiga",
    ],
    Huaral: [
      "Atavillos Alto",
      "Atavillos Bajo",
      "Aucallama",
      "Chancay",
      "Huaral",
      "Ihuarí",
      "Lampían",
      "Pacaraos",
      "San Miguel de Acos",
      "Santa Cruz de Andamarca",
      "Sumbilca",
      "Veintisiete de Noviembre",
    ],
    Huarochirí: [
      "Antioquía",
      "Callahuanca",
      "Carampoma",
      "Chicla",
      "Cuenca",
      "Huachupampa",
      "Huanza",
      "Huarochirí",
      "Lahuaytambo",
      "Langa",
      "Laraos",
      "Mariatana",
      "Matucana",
      "Ricardo Palma",
      "San Andrés de Tupicocha",
      "San Antonio de Chaclla",
      "San Bartolomé",
      "San Damián",
      "San Jerónimo de Surco",
      "San Juan de Iris",
      "San Juan de Tantaranche",
      "San Lorenzo de Quinti",
      "San Mateo",
      "San Mateo de Otao",
      "San Pedro de Casta",
      "San Pedro de Huancayre",
      "Sangallaya",
      "Santa Cruz de Cocachacra",
      "Santa Eulalia",
      "Santiago de Anchucaya",
      "Santiago de Tuna",
      "Santo Domingo de los Olleros",
    ],
    Huaura: [
      "Caleta de Carquín",
      "Checras",
      "Huacho",
      "Hualmay",
      "Huaura",
      "Leoncio Prado",
      "Paccho",
      "Santa Leonor",
      "Santa María",
      "Sayán",
      "Vegueta",
      "Ámbar",
    ],
    Oyón: ["Andajes", "Caujul", "Cochamarca", "Naván", "Oyón", "Pachangara"],
    Yauyos: [
      "Alis",
      "Ayauca",
      "Ayaviri",
      "Azángaro",
      "Cacra",
      "Carania",
      "Catahuasi",
      "Chocos",
      "Cochas",
      "Colonia",
      "Hongos",
      "Huampara",
      "Huancaya",
      "Huangascar",
      "Huantán",
      "Huañec",
      "Laraos",
      "Lincha",
      "Madean",
      "Miraflores",
      "Omas",
      "Putinza",
      "Quinches",
      "Quinocay",
      "San Joaquín",
      "San Pedro de Pilas",
      "Tanta",
      "Tauripampa",
      "Tomas",
      "Tupe",
      "Vitis",
      "Viñac",
      "Yauyos",
    ],
  },
  Loreto: {
    "Alto Amazonas": [
      "Balsapuerto",
      "Barranca",
      "Cahuapanas",
      "Jeberos",
      "Lagunas",
      "Manseriche",
      "Morona",
      "Pastaza",
      "Santa Cruz",
      "Teniente César López Rojas",
      "Yurimaguas",
    ],
    "Datem del Marañón": [
      "Andoas",
      "Barranca",
      "Cahuapanas",
      "Manseriche",
      "Morona",
      "Pastaza",
      "San Lorenzo",
    ],
    Loreto: ["Nauta", "Parinari", "Tigre", "Trompeteros", "Urarinas"],
    "Mariscal Ramón Castilla": [
      "Caballococha",
      "Pebas",
      "Ramón Castilla",
      "San Pablo",
      "Yavari",
    ],
    Maynas: [
      "Alto Nanay",
      "Belen",
      "Fernando Lores",
      "Indiana",
      "Iquitos",
      "Las Amazonas",
      "Mazán",
      "Napo",
      "Punchana",
      "Putumayo",
      "San Juan Bautista",
      "Tnte. Manuel Clavero",
      "Torres Causana",
    ],
    Putumayo: [],
    Requena: [
      "Alto Tapiche",
      "Capelo",
      "Emilio San Martín",
      "Jenaro Herrera",
      "Maquía",
      "Puinahua",
      "Requena",
      "Sapuena",
      "Soplin",
      "Tapiche",
      "Yaquerana",
    ],
    Ucayali: [
      "Contamana",
      "Inahuaya",
      "Padre Márquez",
      "Pampa Hermosa",
      "Sarayacu",
      "Vargas Guerra",
    ],
  },
  "Madre De Dios": {
    Manu: ["Fitzcarrald", "Huepetuhe", "Madre de Dios", "Manu"],
    Tahuamanu: ["Iberia", "Iñapari", "Tahuamanu"],
    Tambopata: [
      "Inambari",
      "Laberinto",
      "Las Piedras",
      "Puerto Maldonado",
      "Tambopata",
    ],
  },
  Moquegua: {
    "General Sánchez Cerro": [
      "Chojata",
      "Coalaque",
      "Ichuña",
      "La Capilla",
      "Lloque",
      "Matalaque",
      "Omate",
      "Puquina",
      "Quinistaquillas",
      "Ubinas",
      "Yunga",
    ],
    IIO: ["El Algarrobal", "Ilo", "Pacocha"],
    "Mariscal Nieto": [
      "Carumas",
      "Cuchumbaya",
      "Moquegua",
      "Samegua",
      "San Cristóbal",
      "Torata",
    ],
  },
  Pasco: {
    "Daniel A. Carrión": [
      "Chacayán",
      "Goyllarisquizga",
      "Paucar",
      "San Pedro de Pillao",
      "Santa Ana de Tusi",
      "Tapuc",
      "Vilcabamba",
      "Yanahuanca",
    ],
    Oxapampa: [
      "Chontabamba",
      "Huancabamba",
      "Oxapampa",
      "Palcazú",
      "Pozuzo",
      "Puerto Bermúdez",
      "Villa Rica",
    ],
    Pasco: [
      "Cerro de Pasco",
      "Chaupimarca",
      "Huachón",
      "Huariaca",
      "Huayllay",
      "Ninacaca",
      "Pallanchacra",
      "Paucartambo",
      "San Francisco de Asís de Yarusyacán",
      "Simón Bolívar",
      "Ticlacayán",
      "Tinyahuarco",
      "Vicco",
      "Yanacancha",
    ],
  },
  Piura: {
    Ayabaca: [
      "Ayabaca",
      "Frías",
      "Jilili",
      "Lagunas",
      "Montero",
      "Pacaipampa",
      "Paimas",
      "Sapillica",
      "Sicches",
      "Suyo",
    ],
    Huancabamba: [
      "Canchaque",
      "El Carmen de la Frontera",
      "Huancabamba",
      "Huarmaca",
      "Lalaquiz",
      "San Miguel del Faique",
      "Sapalache",
      "Sondor",
      "Sondorillo",
    ],
    Morropón: [
      "Buenos Aires",
      "Chalaco",
      "Chulucanas",
      "La Matanza",
      "Morropón",
      "Salitral",
      "San Juan de Bigote",
      "Santa Catalina de Mossa",
      "Santo Domingo",
      "Yamango",
    ],
    Paita: [
      "Amotape",
      "Colan",
      "El Arenal",
      "La Huaca",
      "Paita",
      "Tamarindo",
      "Vichayal",
    ],
    Piura: [
      "Castilla",
      "Catacaos",
      "Cura Mori",
      "El Tallán",
      "La Arena",
      "La Unión",
      "Las Lomas",
      "Piura",
      "Tambo Grande",
    ],
    Sechura: [
      "Bellavista de la Unión",
      "Bernal",
      "Cristo nos Valga",
      "Rinconada Llicuar",
      "Sechura",
      "Vice",
    ],
    Sullana: [
      "Bellavista",
      "Ignacio Escudero",
      "Lancones",
      "Marcavelica",
      "Miguel Checa",
      "Querecotillo",
      "Salitral",
      "Sullana",
    ],
    Talara: [
      "El Alto",
      "La Brea",
      "Lobitos",
      "Los Órganos",
      "Máncora",
      "Pariñas",
      "Talara",
    ],
  },
  Puno: {
    Azángaro: [
      "Achaya",
      "Arapa",
      "Asillo",
      "Azángaro",
      "Caminaca",
      "Chupa",
      "José Domingo Choquehuanca",
      "Muñani",
      "Potoni",
      "Saman",
      "San Antón",
      "San José",
      "San Juan de Salinas",
      "Santiago de Pupuja",
      "Tirapata",
    ],
    Carabaya: [
      "Ajoyani",
      "Ayapata",
      "Coasa",
      "Corani",
      "Crucero",
      "Ituata",
      "Macusani",
      "Ollachea",
      "San Gabán",
      "Usicayos",
    ],
    Chucuito: [
      "Desaguadero",
      "Huacullani",
      "Juli",
      "Kelluyo",
      "Pisacoma",
      "Pomata",
      "Zepita",
    ],
    "El Collao": ["Capazo", "Conduriri", "Ilave", "Pilcuyo", "Santa Rosa"],
    Huancané: [
      "Cojata",
      "Huancané",
      "Huatasani",
      "Inchupalla",
      "Pusi",
      "Rosaspata",
      "Taraco",
      "Vilque Chico",
    ],
    Lampa: [
      "Cabanilla",
      "Calapuja",
      "Lampa",
      "Nicasio",
      "Ocuviri",
      "Palca",
      "Paratia",
      "Pucará",
      "Santa Lucía",
      "Vilavila",
    ],
    Melgar: [
      "Antauta",
      "Ayaviri",
      "Cupi",
      "Llalli",
      "Macari",
      "Orurillo",
      "Santa Rosa",
      "Umachiri",
      "Ñuñoa",
    ],
    Moho: ["Conina", "Huayrapata", "Moho", "Tilali"],
    Puno: [
      "Acora",
      "Amantani",
      "Atuncolla",
      "Capachica",
      "Chucuito",
      "Coata",
      "Huata",
      "Mañazo",
      "Paucarcolla",
      "Pichacani",
      "Platería",
      "Puno",
      "San Antonio",
      "Tiquillaca",
      "Vilque",
    ],
    "San Antonio de Putina": [
      "Ananea",
      "Pedro Vilca Apaza",
      "Putina",
      "Quilcapuncu",
      "Sina",
    ],
    "San Román": ["Cabana", "Cabanillas", "Caracoto", "Juliaca"],
    Sandia: [
      "Alto Inambari",
      "Cuyocuyo",
      "Limbani",
      "Patambuco",
      "Phara",
      "Quiaca",
      "San Juan del Oro",
      "San Pedro de Putina Punco",
      "Sandia",
      "Yanahuaya",
    ],
    Yunguyo: [
      "Anapia",
      "Copani",
      "Cuturapi",
      "Ollaraya",
      "Tinicachi",
      "Unicachi",
      "Yunguyo",
    ],
  },
  "San Martin": {
    Bellavista: [
      "Alto Biavo",
      "Bajo Biavo",
      "Bellavista",
      "Huallaga",
      "San Pablo",
      "San Rafael",
    ],
    "El Dorado": [
      "Agua Blanca",
      "San José de Sisa",
      "San Martín",
      "Santa Rosa",
      "Shantoja",
    ],
    Huallaga: [
      "Alto Saposoa",
      "El Eslabón",
      "Piscoyacu",
      "Sacanche",
      "Saposoa",
      "Tingo de Saposoa",
    ],
    Lamas: [
      "Alonso de Alvarado",
      "Barranquita",
      "Caynarachi",
      "Cuñumbuqui",
      "Lamas",
      "Pinto Recodo",
      "Rumisapa",
      "San Roque de Cumbaza",
      "Shanao",
      "Tabalosos",
      "Zapatero",
    ],
    "Mariscal Cáceres": [
      "Campanilla",
      "Huicungo",
      "Juanjui",
      "Juanjuicillo",
      "Pachiza",
      "Pajarillo",
    ],
    Moyobamba: [
      "Calzada",
      "Habana",
      "Jepelacio",
      "Moyobamba",
      "Soritor",
      "Yantalo",
    ],
    Picota: [
      "Buenos Aires",
      "Caspisapa",
      "Picota",
      "Pilluana",
      "Pucacaca",
      "San Cristóbal",
      "San Hilarión",
      "Shamboyacu",
      "Tingo de Ponasa",
      "Tres Unidos",
    ],
    Rioja: [
      "Awajún",
      "Elías Soplín Vargas",
      "Nueva Cajamarca",
      "Pardo Miguel",
      "Posic",
      "Rioja",
      "San Fernando",
      "Yorongos",
      "Yuracyacu",
    ],
    "San Martín": [
      "Alberto Leveau",
      "Cacatachi",
      "Chazuta",
      "Chipurana",
      "El Porvenir",
      "Huimbayoc",
      "Juan Guerra",
      "La Banda de Shilcayo",
      "Morales",
      "Papaplaya",
      "San Antonio",
      "Sauce",
      "Shapaja",
      "Tarapoto",
    ],
    Tocache: ["Nuevo Progreso", "Pólvora", "Shunte", "Tocache", "Uchiza"],
  },
  Tacna: {
    Candarave: [
      "Cairani",
      "Camilaca",
      "Candarave",
      "Curibaya",
      "Huanuara",
      "Quilahuani",
    ],
    "Jorge Basadre": ["Ilabaya", "Ite", "Locumba"],
    Tacna: [
      "Alto de la Alianza",
      "Calana",
      "Ciudad Nueva",
      "Coronel Gregorio Albarracín Lanchipa",
      "Inclán",
      "Pachía",
      "Palca",
      "Pocollay",
      "Sama",
      "Tacna",
    ],
    Tarata: [
      "Chucatamani",
      "Estique",
      "Estique-Pampa",
      "Sitajara",
      "Susapaya",
      "Tarata",
      "Tarucachi",
      "Ticaco",
    ],
  },
  Tumbes: {
    "Contralmirante Villar": ["Canoas de Punta Sal", "Casitas", "Zorritos"],
    Tumbes: [
      "Corrales",
      "La Cruz",
      "Pampas de Hospital",
      "San Jacinto",
      "San Juan de la Virgen",
      "Tumbes",
    ],
    Zarumilla: ["Aguas Verdes", "Matapalo", "Papayal", "Zarumilla"],
  },
  Ucayali: {
    Atalaya: ["Atalaya", "Raymondi", "Sepahua", "Tahuanía", "Yurúa"],
    "Coronel Portillo": [
      "Callería",
      "Campoverde",
      "Iparía",
      "Manantay",
      "Masisea",
      "Nueva Requena",
      "Pucallpa",
      "Yarinacocha",
    ],
    "Padre Abad": ["Aguaytía", "Curimaná", "Irazola", "Padre Abad"],
    Purús: ["Esperanza", "Purús"],
  },
};
